http:
  port: ':8081'
  timeout: '30s'
  shutdown_timeout: '30s'
  read_timeout: '15s'
  write_timeout: '60s'

db:
  host: 'localhost'
  port: '5432'
  db_name: 'postgres'
  username: 'postgres'
  migration_path: 'migrations/pg'
  migration_version: 3

token:
  time_to_live: "15m"